apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Burguer404
  template:
    metadata:
      labels:
        app: Burguer404
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
                name: db-password
                key: SA_PASSWORD
        volumeMounts:
        - name: mssql-data
          mountPath: /var/opt/mssql
      volumes:
      - name: mssql-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: burguer404-service
spec:
  selector:
    app: Burguer404
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433
  type: ClusterIP
