apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Burguer404
  template:
    metadata:
      labels:
        app: Burguer404
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ACCEPT_EULA
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: SA_PASSWORD
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "2Gi"
        volumeMounts:
        - name: mssql-data
          mountPath: /var/opt/mssql
      volumes:
      - name: mssql-data
        emptyDir: {}
