apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  SA_PASSWORD: QnVyZ3VlcjQwNEAyMDI1
  ConnectionStrings__DefaultConnection: U2VydmVyPWRiLWJ1cmd1ZXI0MDQtc2VydmljZTtEYXRhYmFzZT1CdXJndWVyNDA0O1VzZXIgSWQ9c2E7UGFzc3dvcmQ9QnVyZ3VlcjQwNEAyMDI1O1RydXN0U2VydmVyQ2VydGlmaWNhdGU9VHJ1ZQ==
