// <auto-generated />
using System;
using Burguer404.Infrastructure.Data.ContextDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Burguer404.Infrastructure.Data.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("CodPedidoSequence", "dbo");

            modelBuilder.Entity("Burguer404.Domain.Entities.ClassesEnums.CategoriaPedidoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CategoriaPedido", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Lanche"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Acompanhamento"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Bebida"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Sobremesa"
                        });
                });

            modelBuilder.Entity("Burguer404.Domain.Entities.ClassesEnums.StatusPedidoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("StatusPedido", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Recebido"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Em preparação"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Pronto"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Finalizado"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Cancelado"
                        });
                });

            modelBuilder.Entity("Burguer404.Domain.Entities.Cliente.ClienteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nchar(14)")
                        .IsFixedLength();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(130)
                        .HasColumnType("nvarchar(130)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("Burguer404.Domain.Entities.Pedido.PedidoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoPedido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusPedidoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("StatusPedidoId");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("Burguer404.Domain.Entities.Pedido.PedidoProdutoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("PedidoProduto", (string)null);
                });

            modelBuilder.Entity("Burguer404.Domain.Entities.Produto.ProdutoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaPedidoId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte[]>("Imagem")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varbinary(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Preco")
                        .HasColumnType("float");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaPedidoId");

                    b.ToTable("Produtos", (string)null);
                });

            modelBuilder.Entity("Burguer404.Domain.Entities.Pedido.PedidoEntity", b =>
                {
                    b.HasOne("Burguer404.Domain.Entities.Cliente.ClienteEntity", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Burguer404.Domain.Entities.ClassesEnums.StatusPedidoEntity", "StatusPedido")
                        .WithMany()
                        .HasForeignKey("StatusPedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("StatusPedido");
                });

            modelBuilder.Entity("Burguer404.Domain.Entities.Pedido.PedidoProdutoEntity", b =>
                {
                    b.HasOne("Burguer404.Domain.Entities.Pedido.PedidoEntity", "Pedido")
                        .WithMany("PedidoProduto")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Burguer404.Domain.Entities.Produto.ProdutoEntity", "Produto")
                        .WithMany("PedidoProduto")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Burguer404.Domain.Entities.Produto.ProdutoEntity", b =>
                {
                    b.HasOne("Burguer404.Domain.Entities.ClassesEnums.CategoriaPedidoEntity", "CategoriaPedido")
                        .WithMany()
                        .HasForeignKey("CategoriaPedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaPedido");
                });

            modelBuilder.Entity("Burguer404.Domain.Entities.Cliente.ClienteEntity", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Burguer404.Domain.Entities.Pedido.PedidoEntity", b =>
                {
                    b.Navigation("PedidoProduto");
                });

            modelBuilder.Entity("Burguer404.Domain.Entities.Produto.ProdutoEntity", b =>
                {
                    b.Navigation("PedidoProduto");
                });
#pragma warning restore 612, 618
        }
    }
}
